FROM node:18.16.0-alpine
WORKDIR /usr/src/app
RUN apk update && apk add bash
COPY package*.json yarn*.lock .npmrc ./
RUN apk add yarn --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
RUN yarn
COPY . .
RUN yarn set version canary
EXPOSE 3000
