"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.Lock__factory = exports.GLDToken__factory = exports.EvidenceRecords__factory = exports.CeeToken__factory = exports.CarbonMintLockedRecordNFT__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CarbonMintLockedRecordNFT__factory_1 = require("./CarbonMintLockedRecordNFT__factory");
__createBinding(exports, CarbonMintLockedRecordNFT__factory_1, "CarbonMintLockedRecordNFT__factory");
var CeeToken__factory_1 = require("./CeeToken__factory");
__createBinding(exports, CeeToken__factory_1, "CeeToken__factory");
var EvidenceRecords__factory_1 = require("./EvidenceRecords__factory");
__createBinding(exports, EvidenceRecords__factory_1, "EvidenceRecords__factory");
var GLDToken__factory_1 = require("./GLDToken__factory");
__createBinding(exports, GLDToken__factory_1, "GLDToken__factory");
var Lock__factory_1 = require("./Lock__factory");
__createBinding(exports, Lock__factory_1, "Lock__factory");
