"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.IAccessControl__factory = exports.AccessControl__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AccessControl__factory_1 = require("./AccessControl__factory");
__createBinding(exports, AccessControl__factory_1, "AccessControl__factory");
var IAccessControl__factory_1 = require("./IAccessControl__factory");
__createBinding(exports, IAccessControl__factory_1, "IAccessControl__factory");
