// Generated by CoffeeScript 2.7.0
(function () {
  var Bottom,
    Composite,
    Middle,
    Page,
    Tag,
    Top,
    Widget,
    YAML,
    container,
    container2,
    dumpHierarchy,
    logo,
    title;

  YAML = require('yaml');

  ({ Widget, Composite, Tag, dumpHierarchy } = require('./functional.rtml'));

  container = Composite(Tag('div'));

  logo = Widget('img', {
    src: '/logo.png',
    width: 64,
    alt: '$p.title',
  });

  title = Tag('title');

  container2 = logo(container);

  console.log(dumpHierarchy(container));

  // container logo
  Top = () => {
    var menu, menuItem1, menuItem2, topArea, topAreaWidget, toprightMenu;
    logo = Widget('img', {
      src: '/logo.png',
      width: 64,
      alt: '$p.title',
    });
    title = Tag('title');
    menu = Tag('$M.Menu');
    menuItem1 = Tag('item1');
    menuItem2 = Tag('item2');
    menu = Composite(menu);
    menu = menu([menuItem1, menuItem2]);
    toprightMenu = Tag('toprightMenu');
    toprightMenu = Composite(toprightMenu);
    toprightMenu = toprightMenu([menu]);
    topAreaWidget = Tag('topArea');
    topArea = Composite(topAreaWidget);
    topArea = topArea([logo, title, toprightMenu]);
    return topArea;
  };

  Middle = () => {
    var ContentArea, LeftMenu, MiddleArea, middleContainer;
    LeftMenu = Tag('LeftMenu');
    ContentArea = Tag('ContentArea');
    middleContainer = Tag('Middle');
    MiddleArea = Composite(middleContainer);
    MiddleArea = MiddleArea([LeftMenu, ContentArea]);
    return MiddleArea;
  };

  Bottom = () => {
    var copyright, footerArea, footerNode, poweredby;
    footerNode = Tag('Footer');
    footerArea = Composite(footerNode);
    copyright = 'copyright 2022';
    poweredby = Tag('poweredby');
    footerArea = footerArea([copyright, poweredby]);
    return footerArea;
  };

  Page = () => {
    var page, root;
    root = Widget('root', {}, []);
    page = Composite(root);
    page = page([Top(), Middle(), Bottom()]);
    return page;
  };

  module.exports = Page;

  // console.log YAML.stringify Page().toObject()
}.call(this));
