// Generated by CoffeeScript 2.7.0
(function () {
  var interpret, jsonify, preadFile, test;

  ({ preadFile } = require('./fsutil'));

  ({ interpret } = require('./lib'));

  jsonify = function (x) {
    return JSON.stringify(x, null, 2);
  };

  test = async function () {
    var content, fn;
    fn = 'specs/src/Layout.rtml.yaml';
    content = await preadFile(fn);
    return console.log(jsonify(interpret(content, fn)));
  };

  test();

  //module.exports = test
}.call(this));
